python classify_image.py --image_file /data/100001.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104004.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/107500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/110702.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/113701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117302.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134503.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136903.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138307.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/142200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146206.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104006.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/107501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/110801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117402.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134603.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138308.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/142700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146302.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149603.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/107800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/110901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114502.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117403.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127403.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/131400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138502.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/142900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146405.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100302.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104202.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/107901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114503.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127503.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/131900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134803.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137502.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138504.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/142901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114504.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121403.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146602.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149902.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100503.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/104802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/122203.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135103.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137603.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/100701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105002.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108105.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/118100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/122301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/125102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/128000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132402.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137704.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138704.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105103.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108202.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/114901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/118302.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/122701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/125501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/128002.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137705.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138708.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147001.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105104.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111702.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/115200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/118303.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/122801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/125600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/128201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132504.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/137800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147103.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101504.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111703.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/115300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/118801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123003.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/125800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/128901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132506.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135502.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138006.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143902.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/111901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/115301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/118900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/125900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129202.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132510.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135702.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138008.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/143903.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101702.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123202.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126002.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/135801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138010.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/139404.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147602.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/101800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/105802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119203.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/132900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136006.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138012.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/139700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144104.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/147800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/102001.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112404.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/133000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136008.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/139901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/148203.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/102400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/108902.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112405.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119602.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/133201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138103.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/140801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/148500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/102402.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/109101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112407.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123602.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/133301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136402.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138105.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/141100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/148600.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/102500.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/109400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116802.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/119703.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126804.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/129901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/133801.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136505.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/141300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/144903.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/148603.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/102501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106602.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/109601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/112901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/120101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130302.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/133900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/141304.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/145200.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/103102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/109800.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/113201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/116901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/120300.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/123901.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/126902.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134003.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136704.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138203.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/141700.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146003.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/103202.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/106703.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/110201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/113402.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/120900.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127001.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130401.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134400.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136803.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/141704.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/103701.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/107000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/110601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/113601.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/117201.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/121101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/124100.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/127101.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/130501.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/134502.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/136804.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/138304.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/142000.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/146102.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw
python classify_image.py --image_file /data/149301.jpg --num_top_predictions 5 >> result.raw && echo ";\n" >> result.raw